services:
  - type: web
    name: Brosis-FrontEnd
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://brosis-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
